name: ElysiaEquipmentSet
version: '${project.version}'
main: com.elysia.elysiaequipmentset.ElysiaEquipmentSet
load: STARTUP
commands:
  ElysiaEquipmentSet:
    permission: admin
    aliases:
      - ees
